### ISSUE TITLE
No exon_ID on results

### ISSUE THREAD

**Issue by guillermomarco** [MIAOKUI/PSI#1]
Hello,
I've been using PSI script with both my own dataset and yours and I'm getting results without "exon_ID". Do you have any idea what could be causing that? Here's the command I'm using with the test dataset you provide.

`psi_shell/PSI_v2.0  StartPSI test/output/genes.gtf 101 test/bam/E19_WT_1.bam test/junctions/E19_WT_1_tnnt2_junctions.bed E19_WT_1_test`

I've attached the head of the PSI result output, [E19_WT_1_test_exonic_parts_head.psi.gz](https://github.com/MIAOKUI/PSI/files/2038152/E19_WT_1_test_exonic_parts_head.psi.gz)

**Comment by pabodha** [comment]
Hi,
You need to use an earlier version of bedtools to get the script to work. Bedtools 2.17.0 works for me. 
Pabodha

**Comment by guillermomarco** [comment]
Thank you!
